config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  devise_for :users, :controllers => {:registrations  => "registrations"}
  root to: 'elections#index'
  get 'ledger', controller: 'pages', action: 'ledger'
  post 'ledger', controller: 'pages', action: 'ledger'
  resources :elections do
    get 'vote/:candidate_id', action: 'vote', as: 'vote'
  end
  resources :candidates
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Digital Voting Platform', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Elections', elections_path, class: 'nav-link' %>
      </li>
      
      <li class="nav-item">
        <%= link_to 'Candidates', candidates_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Ledger', ledger_path, class: 'nav-link' %>
      </li>
      <%= render navbar_links_partial %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= yield :title %>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        </p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger">
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        </p>
      <% end %>

      <div class="card">
        <div class="card-header">
            <h1 class="text-primary text-center"><%= yield :title %></h1>
        </div>
        <div class="card-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>